repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format Rust code
        entry: cargo fmt --check
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        description: Lint Rust code
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-test
        name: cargo test
        description: Test Rust code
        entry: cargo test --all-features --all-targets
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-deny
        name: cargo deny
        description: Check dependency advisories and licenses
        entry: cargo +stable deny check advisories licenses
        language: system
        pass_filenames: false
        stages: [pre-push]
