[advisories]
unmaintained = "workspace"
unsound = "workspace"
yanked = "warn"
unused-ignored-advisory = "deny"

[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "Unlicense",
]
confidence-threshold = 0.8
